config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :pharmacies
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
	has_many :pharmacies


	#validates :nome, presence: true

	validates :ibge, presence: true, uniqueness: {case_sensitive: true}, numericality: {only_integer: true}
	validates :uf, presence: true, length: {is: 2}
	validates :cidade, presence: true
	validates :nome, presence: true, length: {in: 3 .. 60}
	validates :endereco, presence: true, length: {in: 3 .. 60}
	validates :bairro, presence: true, length: {in: 3 .. 40}
	validates :cep, presence: true, numericality: {only_integer: true}, length:{is: 8}
	validates :ddd, length:{in: 2 .. 3}
	validates :telefone, presence: true, numericality: {only_integer: true}
	validates :email, presence: true
	validates :cnpj_farmacia, presence: true, numericality: {only_integer: true}
	validates :cnpj_matriz, presence: true, numericality: {only_integer: true}
	validates :ano, presence: true
	validates :mes, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  before_action :set_pharmacy, only: [:show, :edit, :update, :destroy]

  # GET /pharmacies
  # GET /pharmacies.json
  def index
    @pharmacies = Pharmacy.all.all.page(
      params[:page]
    ).per(20)

  end

  # GET /pharmacies/1
  # GET /pharmacies/1.json
  def show
  end

  # GET /pharmacies/new
  def new
    @pharmacy = Pharmacy.new
  end

  # GET /pharmacies/1/edit
  def edit
  end

  # POST /pharmacies
  # POST /pharmacies.json
  def create
    @pharmacy = Pharmacy.new(pharmacy_params)

    respond_to do |format|
      if @pharmacy.save
        format.html { redirect_to @pharmacy, notice: 'Pharmacy was successfully created.' }
        format.json { render :show, status: :created, location: @pharmacy }
      else
        format.html { render :new }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pharmacies/1
  # PATCH/PUT /pharmacies/1.json
  def update
    respond_to do |format|
      if @pharmacy.update(pharmacy_params)
        format.html { redirect_to @pharmacy, notice: 'Pharmacy was successfully updated.' }
        format.json { render :show, status: :ok, location: @pharmacy }
      else
        format.html { render :edit }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pharmacies/1
  # DELETE /pharmacies/1.json
  def destroy
    @pharmacy.destroy
    respond_to do |format|
      format.html { redirect_to pharmacies_url, notice: 'Pharmacy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharmacy
      @pharmacy = Pharmacy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pharmacy_params
      params.require(:pharmacy).permit(:ibge, :uf, :cidade, :nome, :endereco, :bairro, :cep, :ddd, :telefone, :email, :cnpj_farmacia, :cnpj_matriz, :ano, :mes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">FP</h1>
    <p class="lead">Farmácia Popular</p>
  </div>
  <a href="http://localhost:3000/pharmacies">Farmácias</a>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">FP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pharmacy_path %>">Farmácia</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pharmacies_path %>">Cadastro</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pharmacies/_form.html.erb
<%= form_with(model: pharmacy, local: true) do |form| %>
  <% if pharmacy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pharmacy.errors.count, "error") %> prohibited this pharmacy from being saved:</h2>

      <ul>
      <% pharmacy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ibge %>
    <%= form.text_field :ibge %>
  </div>

  <div class="field">
    <%= form.label :uf %>
    <%= form.text_field :uf %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :ddd %>
    <%= form.number_field :ddd %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cnpj_farmacia %>
    <%= form.text_field :cnpj_farmacia %>
  </div>

  <div class="field">
    <%= form.label :cnpj_matriz %>
    <%= form.text_field :cnpj_matriz %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano %>
  </div>

  <div class="field">
    <%= form.label :mes %>
    <%= form.number_field :mes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pharmacies/edit.html.erb
<h1>Editing Pharmacy</h1>

<%= render 'form', pharmacy: @pharmacy %>

<%= link_to 'Show', @pharmacy %> |
<%= link_to 'Back', pharmacies_path %>

app/views/pharmacies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pharmacies</h1>

<table>
  <thead>
    <tr>
      <th>Ibge</th>
      <th>Uf</th>
      <th>Cidade</th>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Bairro</th>
      <th>Cep</th>
      <th>Ddd</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Cnpj farmacia</th>
      <th>Cnpj matriz</th>
      <th>Ano</th>
      <th>Mes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pharmacies.each do |pharmacy| %>
      <tr>
        <td><%= pharmacy.ibge %></td>
        <td><%= pharmacy.uf %></td>
        <td><%= pharmacy.cidade %></td>
        <td><%= pharmacy.nome %></td>
        <td><%= pharmacy.endereco %></td>
        <td><%= pharmacy.bairro %></td>
        <td><%= pharmacy.cep %></td>
        <td><%= pharmacy.ddd %></td>
        <td><%= pharmacy.telefone %></td>
        <td><%= pharmacy.email %></td>
        <td><%= pharmacy.cnpj_farmacia %></td>
        <td><%= pharmacy.cnpj_matriz %></td>
        <td><%= pharmacy.ano %></td>
        <td><%= pharmacy.mes %></td>
        <td><%= link_to 'Show', pharmacy %></td>
        <td><%= link_to 'Edit', edit_pharmacy_path(pharmacy) %></td>
        <td><%= link_to 'Destroy', pharmacy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pharmacy', new_pharmacy_path %>

app/views/pharmacies/new.html.erb
<h1>New Pharmacy</h1>

<%= render 'form', pharmacy: @pharmacy %>

<%= link_to 'Back', pharmacies_path %>

app/views/pharmacies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ibge:</strong>
  <%= @pharmacy.ibge %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @pharmacy.uf %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @pharmacy.cidade %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @pharmacy.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @pharmacy.endereco %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @pharmacy.bairro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @pharmacy.cep %>
</p>

<p>
  <strong>Ddd:</strong>
  <%= @pharmacy.ddd %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @pharmacy.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pharmacy.email %>
</p>

<p>
  <strong>Cnpj farmacia:</strong>
  <%= @pharmacy.cnpj_farmacia %>
</p>

<p>
  <strong>Cnpj matriz:</strong>
  <%= @pharmacy.cnpj_matriz %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @pharmacy.ano %>
</p>

<p>
  <strong>Mes:</strong>
  <%= @pharmacy.mes %>
</p>

<%= link_to 'Edit', edit_pharmacy_path(@pharmacy) %> |
<%= link_to 'Back', pharmacies_path %>